name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: 'google-cloud-auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.IMAGE_REGISTRY_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Login to Docker registry'
        run: 'gcloud auth configure-docker europe-west1-docker.pkg.dev'

      - name: Get the version
        id: find-version
        run: |
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          echo "::set-output name=version::$PACKAGE_VERSION"

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag europe-west1-docker.pkg.dev/lunch-break-project/lunch-break/lunch-break:${{ steps.find-version.outputs.version }}
          docker push europe-west1-docker.pkg.dev/lunch-break-project/lunch-break/lunch-break:${{ steps.find-version.outputs.version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.CD_SERVICE_ACCOUNT_KEY }}'

      - name: Get the version
        id: find-version
        run: |
          PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
          echo "::set-output name=version::$PACKAGE_VERSION"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          image: europe-west1-docker.pkg.dev/lunch-break-project/lunch-break/lunch-break:${{ steps.find-version.outputs.version }}
          service: lunch-break
          region: europe-west1
